const CartActionsTypes = {
  TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  REMOVE_ITEM_BY_QUANTITY: 'REMOVE_ITEM_BY_QUANTITY',
};

export default CartActionsTypes;
